name: Compile and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the code
        uses: actions/checkout@v5.0.0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Getting the dependencies
        run: dotnet restore

      - name: Compile
        run: dotnet build --no-restore

    
     
